ascii <- function(x) !any(grepl("[^\\x01-\\x7f]", as.character(x), perl = TRUE))

test_that("algorithm() of RTMB fits: AGHQ, Laplace and ELGM", {
  skip_if_not_installed("RTMB")
  set.seed(1); d <- sim_rtirt(N = 200, K = 3)
  m <- rtirt_syntax(paste0("y", 1:3), paste0("t", 1:3))
  fa <- suppressWarnings(birt(m, d, engine = "rtmb", progress = FALSE, control = rtmb_control(method = "aghq")))
  u <- as.character(algorithm(fa))
  expect_s3_class(algorithm(fa), "birt_algorithm")
  expect_true(any(grepl("^1\\. Person latents", u)))
  expect_true(any(grepl(sprintf("k = %d", fa$rtmb$k), u, fixed = TRUE)))
  expect_true(any(grepl("Optimization rounds", u, fixed = TRUE)))
  expect_true(any(grepl("accuracy check", u, fixed = TRUE)))
  l <- as.character(algorithm(fa, "latex"))
  expect_equal(l[1], "\\begin{aligned}"); expect_equal(l[length(l)], "\\end{aligned}"); expect_true(ascii(l))
  fl <- suppressWarnings(birt(m, d, engine = "rtmb", control = rtmb_control(method = "laplace"), progress = FALSE))
  u <- as.character(algorithm(fl))
  expect_true(any(grepl("sdreport", u, fixed = TRUE))); expect_false(any(grepl("Optimization rounds", u, fixed = TRUE)))
  fe <- suppressWarnings(birt(m, d, engine = "rtmb", control = rtmb_control(method = "elgm"), progress = FALSE))
  u <- as.character(algorithm(fe))
  expect_true(any(grepl(sprintf("Outer quadrature over the parameters (%d nodes)", length(fe$rtmb$elgm$prob)), u, fixed = TRUE)))
  expect_true(any(grepl(sprintf("%.2f", fe$rtmb$elgm$lognc), u, fixed = TRUE)))
  expect_true(any(grepl("Cornish-Fisher", u, fixed = TRUE)))
  # the rounds of ELGM maximize log L + log prior, and are labelled so
  qc <- grep("accuracy check", u, value = TRUE)
  expect_match(qc, "-2 log L - 2 log prior", fixed = TRUE)
  expect_match(qc, format(round(-2 * fe$rtmb$logpost, 3), nsmall = 3), fixed = TRUE)
  expect_false(any(grepl("accuracy check: -2 log L =", u, fixed = TRUE)))
  expect_true(any(grepl("accuracy check: -2 log L =", as.character(algorithm(fa)), fixed = TRUE)))
  expect_true(ascii(algorithm(fe, "latex")))
})

test_that("algorithm() of ordinal fits and the default method", {
  skip_if_not_installed("RTMB")
  d <- sim_hgrm(N = 150, J = 4)
  o <- suppressWarnings(birt("theta =~ y1 + y2 + y3 + y4", d, ordered = TRUE, engine = "rtmb", progress = FALSE, control = rtmb_control(method = "aghq")))
  u <- as.character(algorithm(o))
  expect_true(any(grepl("graded response", u, fixed = TRUE)))
  expect_true(any(grepl("Optimization rounds", u, fixed = TRUE)))
  expect_true(ascii(algorithm(o, "latex")))
  expect_error(algorithm(1), "needs a fit")
})

test_that("algorithm() of JAGS fits lists the samplers", {
  skip_on_cran()
  skip_if(Sys.which("jags") == "", "JAGS not installed")
  skip_if_not_installed("rjags")
  d <- sim_rtirt(N = 100, K = 3)
  f <- birt(rtirt_syntax(paste0("y", 1:3), paste0("t", 1:3)), d, n_chains = 2, n_iter = 200, n_burn = 100,
            fit_indices = FALSE, progress = FALSE, engine = "jags")
  u <- as.character(algorithm(f))
  expect_true(any(grepl("Samplers assigned by JAGS", u, fixed = TRUE)))
  expect_true(any(grepl("RealSlicer", u, fixed = TRUE)))
  expect_true(any(grepl("ability[1:100]", u, fixed = TRUE)))
  expect_true(any(grepl("100 adaptation iterations", u, fixed = TRUE)))
  expect_false(any(grepl("RealSlicer", as.character(algorithm(f, samplers = FALSE)), fixed = TRUE)))
  expect_true(ascii(algorithm(f, "latex")))
  skip_if_not_installed("RTMB")
  h <- hgrm("theta =~ y1 + y2 + y3 + y4", sim_hgrm(N = 100, J = 4), moderators = "logT", progress = FALSE, control = rtmb_control(method = "aghq"))
  expect_s3_class(h, "birt_rtmb"); expect_true(any(grepl("Gauss-Hermite", as.character(algorithm(h)), fixed = TRUE)))
})
