test_that("casewise scores of RTMB fits are the per-person gradients", {
  skip_if_not_installed("RTMB")
  set.seed(4)
  d <- sim_rtirt(N = 200, K = 4)
  f <- birt(rtirt_syntax(paste0("y", 1:4), paste0("t", 1:4), cross = "free"), d, engine = "rtmb", progress = FALSE, control = rtmb_control(method = "aghq"))
  S <- estfun.birt_rtmb(f); info <- attr(S, "parameters")
  expect_equal(dim(S), c(200, length(unlist(f$rtmb$par))))
  expect_setequal(unique(info$block), c("measurement", "rt", "structural"))
  ns <- asNamespace("birt"); pf <- f$rtmb$par; x0 <- unlist(pf, use.names = FALSE)
  ND <- ns$node_data(f$S, f$rtmb$centers, f$rtmb$k)
  g <- function(v) { p <- ns$unpack_par(v, pf); ll <- matrix(ns$ind_ll(p, f$S, ns$lat_values(p, f$S, ND$z1, ND$z2, ND$rows), ND$rows) + ND$lw, 200)
    m <- apply(ll, 1, max); m + log(rowSums(exp(ll - m))) + ND$cst }
  expect_equal(sum(g(x0)), -f$rtmb$objective, tolerance = 1e-8)
  j <- 1; h <- 1e-5; e <- replace(numeric(length(x0)), j, h)
  expect_lt(max(abs(S[, j] - (g(x0 + e) - g(x0 - e)) / (2 * h))), 1e-6)
})

test_that("score_test() for RTMB fits: blocks, items, impact message, refusals", {
  skip_if_not_installed("RTMB"); skip_if_not_installed("strucchange")
  set.seed(5)
  d <- sim_rtirt(N = 300, K = 4)
  f <- birt(rtirt_syntax(paste0("y", 1:4), paste0("t", 1:4)), d, engine = "rtmb", progress = FALSE, control = rtmb_control(method = "aghq"))
  r <- score_test(f, rbinom(300, 1, 0.5) == 1, by_item = TRUE, impact_check = FALSE)
  expect_s3_class(r, "birt_score_test"); expect_equal(attr(r, "test"), "LM")
  expect_equal(r$parameters[-1], paste0("y", 1:4)); expect_true(all(r$p.value >= 0 & r$p.value <= 1))
  expect_output(print(r), "LM test")
  expect_equal(attr(score_test(f, rowSums(d[paste0("t", 1:4)]), parm = "measurement"), "test"), "DM")
  expect_message(score_test(f, d$y1 + d$y2 + d$y3 + d$y4), "latent regression")
  expect_error(score_test(f, 1:10), "persons")
  expect_error(score_test(f, rnorm(300), cluster = rep(1:30, each = 10)), "constant within clusters")
  expect_error(score_test(1), "maximum likelihood fit")
})

test_that("the score tools refuse ELGM and Laplace fits with the maximum likelihood route", {
  skip_if_not_installed("RTMB")
  d <- sim_rtirt(N = 200, K = 3, seed = 4)
  m <- rtirt_syntax(paste0("y", 1:3), paste0("t", 1:3))
  fe <- birt(m, d, progress = FALSE)
  for (fn in list(function() score_test(fe, d$x1), function() quantile_score(fe), function() estfun.birt_rtmb(fe)))
    expect_error(fn(), "maximum likelihood tool .*ELGM fit: refit the same model with control = rtmb_control\\(method = \"aghq\"\\).*compare\\(\\)")
  fl <- birt(m, d, control = rtmb_control(method = "laplace"), progress = FALSE)
  expect_error(score_test(fl, d$x1), "needs the AGHQ maximum likelihood fit")
  skip_if_not_installed("partykit")
  expect_error(dif_tree(m, d, data.frame(g = d$x1), control = rtmb_control()), "maximum likelihood")
})
