#' RTMB code of a model
#'
#' The counterpart of [jags_code()] for `engine = "rtmb"`: writes a standalone R script
#' with the model written out item by item (the joint log density of one person given the
#' standard-normal latent values), the Laplace fit and the AGHQ refinement. It expects the
#' data frame as `data`; parameter names and starting values are those of [birt()], so
#' `fit$rtmb$par` can be plugged in; from a fit, the script starts at its estimates. As in
#' birt, the SHASH shapes are bounded and the full model starts from the normal one (birt
#' also halves the step when an AGHQ round does not improve).
#' @param x A `birt_rtmb` fit, or model syntax.
#' @param data,binary,family,log_rt,ordered,itemtype,censor As in [birt()] (when `x` is syntax).
#' @param estimate Include the fitting part (Laplace and AGHQ); `FALSE` gives the model only.
#' @param k AGHQ nodes per latent dimension (default as in [rtmb_control()]).
#' @param file Optional file to write the script to.
#' @return The script (character), printed with `cat()`.
#' @examples
#' \donttest{
#' if (requireNamespace("RTMB", quietly = TRUE)) {
#'   d <- sim_rtirt(K = 5)
#'   f <- birt(rtirt_syntax(paste0("y", 1:5), paste0("t", 1:5), cross = "free"), d,
#'             control = rtmb_control(method = "aghq"), progress = FALSE)
#'   path <- file.path(tempdir(), "model_rtmb.R")
#'   rtmb_code(f, file = path)               # then: data <- d; source(path)
#' }
#' }
#' @export
rtmb_code <- function(x, data = NULL, binary = NULL, family = NULL, log_rt = FALSE, ordered = NULL, itemtype = "grm", censor = NULL,
                      estimate = TRUE, k = NULL, file = NULL) {
  if (inherits(x, "birt_rtmb") && !is.null(x$rtmb$elgm))
    message("rtmb_code() writes the maximum-likelihood script (starting at the posterior mode); the ELGM priors and outer quadrature are not included")
  if (inherits(x, "birt_rtmb")) { S <- x$S; logv <- x$spec$log_rt; k <- k %||% x$rtmb$k; S$par0 <- x$rtmb$par; from_fit <- TRUE }
  else {
    if (is.null(data)) stop("rtmb_code(): `data` is needed to build the code from syntax")
    if (isTRUE(log_rt) && !is.null(ordered) && !isFALSE(ordered))
      stop("with ordinal indicators give log_rt as the column names of the times to log-transform", call. = FALSE)
    data <- log_columns(data, log_rt, x)
    sp <- build_spec(x, data, binary, family, ordered, itemtype); logv <- attr(data, "birt_log_rt")
    sp$censor <- censor_setup(censor, sp, data, logv)
    S <- rtmb_build(sp, data); from_fit <- FALSE
  }
  k <- k %||% if (S$nF == 1) 21L else 9L
  lv <- if (inherits(x, "birt_rtmb")) x$spec$ord$levels else sp$ord$levels
  code <- rtmb_script(S, logv, estimate, k, from_fit, lv)
  if (!is.null(file)) writeLines(code, file)
  cat(code)
  invisible(code)
}

rtmb_script <- function(S, logv, estimate, k, from_fit = FALSE, levels = list()) {
  fs <- S$fs; nF <- S$nF; ld <- S$ld
  q <- function(v) sprintf('"%s"', v)
  vec <- function(v) if (!length(v)) "numeric(0)" else sprintf("c(%s)", paste(num(round(v, 4)), collapse = ", "))
  modval <- function(m) if (m %in% fs) m else sprintf('X[, %s]', q(m))
  modsum_txt <- function(coef, idx, m) paste(sprintf(" + %s[%d] * %s", coef, idx, vapply(m, modval, "")), collapse = "")
  # moderation (E() statements): the sum of the effects on indicator v of one kind, as in mod_eff()
  mod_txt <- function(v, kind, f = "") {
    if (is.null(S$mod)) return("")
    m <- S$mod[S$mod$target == v & S$mod$kind == kind & (kind == "beta" | S$mod$factor == f), ]
    if (!nrow(m)) return("")
    paste(sprintf("p$%s[%d] * X[, %s]", m$par, m$idx, q(m$mod)), collapse = " + ")
  }
  lam_txt <- function(r) {
    l <- switch(ld$kind[r], fixed = num(ld$value[r]), pos = sprintf("exp(p$lpos[%d])", ld$idx[r]), real = sprintf("p$lreal[%d]", ld$idx[r]))
    a <- mod_txt(ld$rhs[r], "alpha", ld$lhs[r])
    if (nzchar(a)) sprintf("%s * exp(%s)", l, a) else l
  }
  load_terms <- function(rows) paste(vapply(rows, function(r) {
    moderated <- nzchar(mod_txt(ld$rhs[r], "alpha", ld$lhs[r]))
    if (!moderated && ld$kind[r] == "fixed" && ld$value[r] == 1) return(sprintf(" + %s", ld$lhs[r]))
    if (!moderated && ld$kind[r] == "fixed" && ld$value[r] == -1) return(sprintf(" - %s", ld$lhs[r]))
    sprintf(" + %s * %s", lam_txt(r), ld$lhs[r]) }, ""), collapse = "")
  latent_txt <- function(mean, ls, u) {               # mean + exp(ls) * u, without zero / unit terms
    if (grepl(" [-+] ", u)) u <- sprintf("(%s)", u)                  # r * z1 + sqrt(1 - r^2) * z2 is one factor
    sc <- if (ls == "0") u else sprintf("exp(%s) * %s", ls, u)
    if (mean == "0") sc else sprintf("%s + %s", mean, sc)
  }
  out <- c(sprintf("# generated by birt %s: RTMB model (engine = \"rtmb\")", pkg_version()),
           "# Expects a data frame `data`. Latent variables are transforms of independent standard normals z1, z2.",
           "library(RTMB)", "")
  if (length(logv)) out <- c(out, sprintf("for (v in c(%s)) data[[v]] <- log(data[[v]])     # log response times", paste(q(logv), collapse = ", ")), "")
  out <- c(out, "## data",
           sprintf("Yb <- as.matrix(data[c(%s)])      # binary indicators", paste(q(S$B), collapse = ", ")),
           if (length(S$C)) sprintf("Yc <- as.matrix(data[c(%s)])      # continuous indicators", paste(q(S$C), collapse = ", ")),
           if (length(S$Xn)) sprintf("X <- as.matrix(data[c(%s)])       # covariates", paste(q(S$Xn), collapse = ", ")) else "X <- matrix(0, nrow(data), 0)",
           "Mb <- 1 * !is.na(Yb); Yb[is.na(Yb)] <- 0              # missing indicators drop out",
           if (length(S$C)) "Mc <- 1 * !is.na(Yc); Yc[is.na(Yc)] <- 0",
           "N <- nrow(Yb)",
           if (length(S$O)) c(
             sprintf("lv <- list(%s)      # ordinal indicators: categories, recoded to 1..K", paste(sprintf("%s = %s", S$O, vapply(S$O, function(v) vec(levels[[v]]), "")), collapse = ", ")),
             "Io <- lapply(names(lv), function(v) { y <- match(data[[v]], lv[[v]]); M <- matrix(0, N, length(lv[[v]])); M[cbind(which(!is.na(y)), y[!is.na(y)])] <- 1; M })",
             "Mo <- 1 * !is.na(as.matrix(data[names(lv)]))"),
           if (!is.null(S$cens)) c(
             "## censored continuous indicators (censor =; limits on the model scale): only beyond the limit is known",
             sprintf("lower <- c(%s); upper <- c(%s)", paste(sprintf("%s = %s", S$C[S$cens$j], num(S$cens$lower)), collapse = ", "),
                     paste(sprintf("%s = %s", S$C[S$cens$j], num(S$cens$upper)), collapse = ", ")),
             "Lc <- Rc <- 0 * Mc",
             "for (v in names(lower)) { j <- match(v, colnames(Yc)); Lc[, j] <- Mc[, j] * (Yc[, j] <= lower[v]); Rc[, j] <- Mc[, j] * (Yc[, j] >= upper[v])",
             "  Yc[Lc[, j] == 1, j] <- lower[v]; Yc[Rc[, j] == 1, j] <- upper[v] }"),
           "",
           "## standardized SHASH: T(u) = {sinh((asinh u + eps) / delta) - sinh(eps / delta)} / k, T(0) = 0, T'(0) = 1",
           "## (eps / delta smoothly bounded at +-8 and the SHASH argument at +-40, as in birt)",
           unlist(lapply(c("ld_sh", "eff_a", "T_std", "ld_std", if (!is.null(S$cens)) "T_inv"), function(n) {      # the functions of birt itself
             d <- deparse(get(n, mode = "function"), control = "digits17"); c(paste(n, "<-", d[1]), d[-1], "") })))
  # parameters
  p0 <- S$par0
  out <- c(out, if (from_fit) "## parameters (starting values: the estimates of the birt fit)" else "## parameters (starting values)", "par <- list(")
  pl <- vapply(names(p0), function(n) sprintf("  %s = %s", n, vec(as.numeric(p0[[n]]))), "")
  pl <- c(pl, "  z1 = rep(0, N)", if (nF == 2) "  z2 = rep(0, N)")
  out <- c(out, paste0(pl, c(rep(",", length(pl) - 1), "")), ")")
  key <- c(
    if (length(p0$lpos)) sprintf("#   lpos[%d]: log of %s", ld$idx[ld$kind == "pos"], paste(ld$lhs, "=~", ld$rhs)[ld$kind == "pos"]),
    if (length(p0$lreal)) sprintf("#   lreal[%d]: %s", ld$idx[ld$kind == "real"], paste(ld$lhs, "=~", ld$rhs)[ld$kind == "real"]),
    if (length(S$B)) sprintf("#   d: intercepts of %s", paste(S$B, collapse = ", ")),
    if (length(S$C)) sprintf("#   xi, lsig: intercepts and log residual SDs of %s", paste(S$C, collapse = ", ")),
    if (length(S$sh)) sprintf("#   eps, ldl: SHASH skewness and log tail weight of %s", paste(S$C[S$sh], collapse = ", ")),
    if (nrow(S$kap)) sprintf("#   kap[%d]: log sd of %s ~ %s", seq_len(nrow(S$kap)), S$C[S$kap$j], S$kap$m),
    if (nrow(S$eta)) sprintf("#   eta[%d]: skew of %s ~ %s", seq_len(nrow(S$eta)), S$C[S$eta$j], S$eta$m),
    if (length(p0$t1)) "#   t1, linc: graded response, first threshold and log increments of the thresholds",
    if (length(p0$pb)) "#   pb: partial credit step difficulties", if (length(p0$lr)) "#   lr: log step-discrimination ratios (tppcm)",
    if (!is.null(S$mod)) sprintf("#   %s[%d]: E(%s) ~ %s", S$mod$par, S$mod$idx, S$mod$target, ifelse(S$mod$kind == "alpha", paste0(S$mod$mod, ":", S$mod$factor), S$mod$mod)))
  out <- c(out, "# parameter key:", unique(key), "")
  # latent values
  f1 <- S$f[[1]]
  lin <- function(i, fi) if (length(fi$covs)) paste(sprintf("p$beta%d[%d] * X[, %s]", i, seq_along(fi$covs), q(fi$covs)), collapse = " + ") else "0"
  ls1 <- paste0(if (f1$free_sd) "p$lsd1" else num(log(f1$sd)), if (length(f1$scale)) modsum_txt("p$alpha1", seq_along(f1$scale), f1$scale) else "")
  body <- c("joint <- function(p, z1, z2, i) {          # log density of persons i at (z1, z2)",
            "  X <- X[i, , drop = FALSE]",
            sprintf("  %s <- %s", fs[1], latent_txt(lin(1, f1), ls1, "z1")))
  if (nF == 2) {
    f2 <- S$f[[2]]
    ls2 <- paste0(if (f2$free_sd) "p$lsd2" else num(log(f2$sd)), if (length(f2$scale)) modsum_txt("p$alpha2", seq_along(f2$scale), f2$scale) else "")
    u <- if (S$cor) "tanh(p$atr) * z1 + sqrt(1 - tanh(p$atr)^2) * z2" else "z2"
    if (f2$shash) u <- sprintf("T_std(%s, p$eps2%s, exp(p$ldl2))", u, if (length(f2$skew)) modsum_txt("p$eta2", seq_along(f2$skew), f2$skew) else "")
    mean2 <- lin(2, f2); if (f2$path) mean2 <- if (mean2 == "0") sprintf("p$gam * %s", fs[1]) else sprintf("%s + p$gam * %s", mean2, fs[1])
    body <- c(body, sprintf("  %s <- %s", fs[2], latent_txt(mean2, ls2, u)))
  }
  body <- c(body, sprintf("  ll <- dnorm(z1, log = TRUE)%s", if (nF == 2) " + dnorm(z2, log = TRUE)" else ""))
  for (j in seq_along(S$B)) {
    rr <- S$ld_b[[j]]; sh <- mod_txt(S$B[j], "beta")
    eta <- sprintf("p$d[%d]%s", j, load_terms(rr))
    if (nzchar(sh)) eta <- sprintf("%s - %s * (%s)", eta, lam_txt(rr[1]), sh)                    # shift on the latent scale
    body <- c(body, sprintf("  ll <- ll + Mb[i, %d] * dbinom_robust(Yb[i, %d], 1, %s, log = TRUE)   # %s", j, j, eta, S$B[j]))
  }
  for (j in seq_along(S$O)) {
    r <- S$ld_o[[j]]; K <- S$K[j]; ix <- S$tix[[j]]; ty <- S$otype[j]; sh <- mod_txt(S$O[j], "beta")
    body <- c(body, sprintf("  # %s: %s, %d categories", S$O[j], switch(ty, grm = "graded response", gpcm = "generalized partial credit", tppcm = "two-parameter partial credit"), K),
              sprintf("  a <- %s; th <- %s%s", lam_txt(r), ld$lhs[r], if (nzchar(sh)) sprintf(" - (%s)", sh) else ""))
    if (ty == "grm") {
      b <- sprintf("p$t1[%d]", ix$t1)
      for (h in seq_len(K - 2)) b <- c(b, sprintf("b%d + exp(p$linc[%d])", h, ix$linc[h]))
      body <- c(body, sprintf("  b%d <- %s", seq_len(K - 1), b),
                sprintf("  P%d <- 1 / (1 + exp(-a * (th - b%d)))           # P(y > %d)", seq_len(K - 1), seq_len(K - 1), seq_len(K - 1)),
                sprintf("  pr <- %s", paste(sprintf("Io[[%d]][i, %d] * (%s - %s)", j, seq_len(K), c("1", sprintf("P%d", seq_len(K - 1))), c(sprintf("P%d", seq_len(K - 1)), "0")), collapse = " +\n        ")),
                sprintf("  ll <- ll + Mo[i, %d] * log(pr + (1 - Mo[i, %d]))", j, j))
    } else {                                                   # adjacent-category logits: log weights lp, log normalizer acc
      body <- c(body, "  lp <- 0; num <- 0; acc <- 0")
      for (h in seq_len(K - 1)) body <- c(body, sprintf("  lp <- lp + a%s * (th - p$pb[%d]); num <- num + Io[[%d]][i, %d] * lp; acc <- acc + log1p(exp(lp - acc))",
                                                       if (ty == "tppcm" && h > 1) sprintf(" * exp(p$lr[%d])", ix$lr[h - 1]) else "", ix$pb[h], j, h + 1))
      body <- c(body, sprintf("  ll <- ll + Mo[i, %d] * (num - acc)", j))
    }
  }
  cj <- if (is.null(S$cens)) integer() else S$cens$j
  for (j in seq_along(S$C)) {
    rr <- S$ld_c[[j]]; kr <- which(S$kap$j == j); s <- match(j, S$sh); er <- which(S$eta$j == j); sh <- mod_txt(S$C[j], "beta")
    ee <- if (!is.na(s)) sprintf("p$eps[%d]%s", s, if (length(er)) modsum_txt("p$eta", er, S$eta$m[er]) else "")
    dens <- if (is.na(s)) sprintf("dnorm(Yc[i, %d], mu, exp(lsc), log = TRUE)", j)
            else sprintf("ld_std((Yc[i, %d] - mu) / exp(lsc), %s, exp(p$ldl[%d])) - lsc", j, ee, s)
    body <- c(body, sprintf("  # %s: %s%s", S$C[j], fam_label(S$famc[[j]]), if (j %in% cj) "; censored" else ""),
              sprintf("  mu <- p$xi[%d]%s%s; lsc <- p$lsig[%d]%s", j, load_terms(rr), if (nzchar(sh)) paste(" +", sh) else "", j,
                      if (length(kr)) modsum_txt("p$kap", kr, S$kap$m[kr]) else ""))
    if (!j %in% cj) { body <- c(body, sprintf("  ll <- ll + Mc[i, %d] * (%s)", j, dens)); next }
    cs <- S$cens[S$cens$j == j, ]; v <- q(S$C[j])
    cdf <- function(lim, up) {
      x <- sprintf("(%s[%s] - mu) / exp(lsc)", lim, v)
      sprintf("pnorm(%s, lower.tail = %s, log.p = TRUE)", if (is.na(s)) x else sprintf("T_inv(%s, %s, exp(p$ldl[%d]))", x, ee, s), if (up) "FALSE" else "TRUE")
    }
    body <- c(body, sprintf("  ll <- ll + Mc[i, %d] * ((1 - Lc[i, %d] - Rc[i, %d]) * (%s)%s%s)", j, j, j, dens,
                            if (is.finite(cs$lower)) sprintf(" +\n                       Lc[i, %d] * %s", j, cdf("lower", FALSE)) else "",
                            if (is.finite(cs$upper)) sprintf(" +\n                       Rc[i, %d] * %s", j, cdf("upper", TRUE)) else ""))
  }
  body <- c(body, "  ll", "}", "",
            "nll <- function(p) {                        # Laplace: z1, z2 are random effects",
            sprintf("  llp <- joint(p, p$z1, %s, seq_len(N)); REPORT(llp)", if (nF == 2) "p$z2" else "0"),
            "  -sum(llp)", "}")
  out <- c(out, "## model", body, "")
  if (!estimate) return(paste0(paste(out, collapse = "\n"), "\n"))
  re <- if (nF == 2) 'c("z1", "z2")' else '"z1"'
  fp <- intersect(fam_pars, names(p0)); fp <- fp[vapply(p0[fp], length, 1L) > 0]
  fit <- c("## bounds of the SHASH shapes: tail weight delta in [1/10, 10], |eps|, |moderation| <= 5",
           "lim <- c(ldl = log(10), ldl2 = log(10), eps = 5, eps2 = 5, eta = 5, eta2 = 5)",
           "bnd <- function(x, s) { b <- rep(s * Inf, length(x)); i <- names(x) %in% names(lim); b[i] <- s * lim[names(x)[i]]; b }",
           "fit_nlminb <- function(o) nlminb(o$par, o$fn, o$gr, lower = bnd(o$par, -1), upper = bnd(o$par, 1),",
           "                                 control = list(eval.max = 3000, iter.max = 2000))", "",
           "## Laplace",
           if (length(fp) && !from_fit) c(sprintf("map0 <- lapply(par[c(%s)], function(v) factor(rep(NA, length(v))))   # normal start", paste(q(fp), collapse = ", ")),
                                          sprintf("obj <- MakeADFun(nll, par, random = %s, map = map0, silent = TRUE); opt <- fit_nlminb(obj)", re),
                                          "par <- obj$env$parList(opt$par)"),
           sprintf("obj <- MakeADFun(nll, par, random = %s, silent = TRUE)", re),
           "opt <- fit_nlminb(obj)",
           "cat(sprintf(\"Laplace -2logL %.3f\\n\", 2 * opt$objective))", "",
           sprintf("## AGHQ: per person a %s rule at the conditional mode, scaled by the inverse Hessian;", if (nF == 2) "k x k product" else "k-node"),
           "## the nodes are data, so the objective is a fixed-effect function; recentre until it stops changing",
           sprintf("k <- %d; gq <- statmod::gauss.quad(k, \"hermite\")", k),
           sprintf("fixed <- setdiff(names(par), %s)", re),
           "modes <- function(pf, z0) {",
           sprintf("  o <- MakeADFun(nll, c(pf, z0), random = %s, silent = TRUE); o$fn(o$par)", re),
           "  lp <- o$env$last.par; zr <- lp[o$env$random]; H <- o$env$spHess(lp, random = TRUE); i <- seq_len(N)",
           if (nF == 2) c("  a <- H[cbind(i, i)]; b <- H[cbind(i, N + i)]; c <- H[cbind(N + i, N + i)]; det <- a * c - b^2",
                          "  l11 <- sqrt(c / det); l21 <- -b / det / l11; l22 <- sqrt(a / det - l21^2)",
                          "  list(m1 = zr[i], m2 = zr[N + i], l11 = l11, l21 = l21, l22 = l22, cst = o$report(lp)$llp, z = list(z1 = zr[i], z2 = zr[N + i]))")
           else "  list(m1 = zr, l11 = 1 / sqrt(H[cbind(i, i)]), cst = o$report(lp)$llp, z = list(z1 = zr))",
           "}",
           "aghq_nll <- function(cn) {",
           if (nF == 2) c("  g <- as.matrix(expand.grid(seq_len(k), seq_len(k))); G <- nrow(g)",
                          "  g1 <- rep(gq$nodes[g[, 1]], each = N); g2 <- rep(gq$nodes[g[, 2]], each = N)",
                          "  z1 <- rep(cn$m1, G) + sqrt(2) * rep(cn$l11, G) * g1",
                          "  z2 <- rep(cn$m2, G) + sqrt(2) * (rep(cn$l21, G) * g1 + rep(cn$l22, G) * g2)",
                          "  lw <- rep(log(gq$weights[g[, 1]] * gq$weights[g[, 2]]) + gq$nodes[g[, 1]]^2 + gq$nodes[g[, 2]]^2, each = N) +",
                          "        rep(log(2 * cn$l11 * cn$l22) - cn$cst, G)")
           else c("  G <- k; g1 <- rep(gq$nodes, each = N); z1 <- rep(cn$m1, G) + sqrt(2) * rep(cn$l11, G) * g1; z2 <- 0",
                  "  lw <- rep(log(gq$weights) + gq$nodes^2, each = N) + rep(log(sqrt(2) * cn$l11) - cn$cst, G)"),
           "  rows <- rep(seq_len(N), G)",
           "  function(p) {",
           "    ll <- joint(p, z1, z2, rows) + lw",
           "    acc <- ll[seq_len(N)]; for (h in seq_len(G)[-1]) acc <- logspace_add(acc, ll[(h - 1) * N + seq_len(N)])",
           "    -sum(acc + cn$cst)",
           "  }",
           "}",
           if (from_fit) sprintf("pf <- par[fixed]; z0 <- par[%s]; prev <- Inf          # AGHQ starts at the birt estimates", re)
           else sprintf("pl <- obj$env$parList(opt$par); pf <- pl[fixed]; z0 <- pl[%s]; prev <- Inf", re),
           "for (r in 1:8) {",
           "  cn <- modes(pf, z0); objA <- MakeADFun(aghq_nll(cn), pf, silent = TRUE)",
           "  optA <- fit_nlminb(objA)",
           "  pf <- objA$env$parList(optA$par); z0 <- cn$z",
           "  cat(sprintf(\"AGHQ round %d: -2logL %.3f\\n\", r, 2 * optA$objective))",
           "  if (abs(prev - optA$objective) < 5e-4) break; prev <- optA$objective",
           "}",
           "se <- sqrt(diag(solve(objA$he(optA$par))))",
           "est <- data.frame(par = names(optA$par), est = optA$par, se = se, row.names = NULL)",
           sprintf("c(minus2logL = 2 * optA$objective, AIC = 2 * optA$objective + 2 * length(optA$par), BIC = 2 * optA$objective + log(N) * length(optA$par))"))
  paste0(paste(c(out, fit), collapse = "\n"), "\n")
}
